module.exports = {
	extends: "eslint:recommended",
	rules: {
		// Disable deprecated rules
		"array-bracket-newline": "off",
		"array-bracket-spacing": "off",
		"array-element-newline": "off",
		"arrow-parens": "off",
		"arrow-spacing": "off",
		"block-spacing": "off",
		"brace-style": "off",
		"comma-dangle": "off",
		"comma-spacing": "off",
		"comma-style": "off",
		"computed-property-spacing": "off",
		"dot-location": "off",
		"eol-last": "off",
		"func-call-spacing": "off",
		"function-call-argument-newline": "off",
		"function-paren-newline": "off",
		"generator-star-spacing": "off",
		"implicit-arrow-linebreak": "off",
		"indent": "off",
		"jsx-quotes": "off",
		"key-spacing": "off",
		"keyword-spacing": "off",
		"linebreak-style": "off",
		"lines-between-class-members": "off",
		"lines-around-comment": "off",
		"max-len": "off",
		"max-statements-per-line": "off",
		"multiline-ternary": "off",
		"new-parens": "off",
		"newline-per-chained-call": "off",
		"no-confusing-arrow": "off",
		"no-extra-parens": "off",
		"no-extra-semi": "off",
		"no-floating-decimal": "off",
		"no-mixed-operators": "off",
		"no-mixed-spaces-and-tabs": "off",
		"no-multi-spaces": "off",
		"no-multiple-empty-lines": "off",
		"no-tabs": "off",
		"no-trailing-spaces": "off",
		"no-whitespace-before-property": "off",
		"nonblock-statement-body-position": "off",
		"object-curly-newline": "off",
		"object-curly-spacing": "off",
		"object-property-newline": "off",
		"one-var-declaration-per-line": "off",
		"operator-linebreak": "off",
		"padded-blocks": "off",
		"padding-line-between-statements": "off",
		"quote-props": "off",
		"quotes": "off",
		"rest-spread-spacing": "off",
		"semi": "off",
		"semi-spacing": "off",
		"semi-style": "off",
		"space-before-blocks": "off",
		"space-before-function-paren": "off",
		"space-in-parens": "off",
		"space-infix-ops": "off",
		"space-unary-ops": "off",
		"spaced-comment": "off",
		"switch-colon-spacing": "off",
		"template-curly-spacing": "off",
		"template-tag-spacing": "off",
		"wrap-iife": "off",
		"wrap-regex": "off",
		"yield-star-spacing": "off",

		// Possible errors
		"no-await-in-loop": "warn",
		"no-control-regex": "warn",
		"no-debugger": "warn",
		"no-empty": "warn",
		"no-extra-boolean-cast": "warn",
		"no-template-curly-in-string": "warn",
		"no-unreachable": "warn",

		// Best practises
		"array-callback-return": "error",
		"block-scoped-var": "warn",
		"consistent-return": "warn",
		"curly": "error",
		"dot-notation": "warn",
		"eqeqeq": ["error", "smart"],
		"guard-for-in": "warn",
		"max-classes-per-file": ["warn", 1],
		"no-alert": "error",
		"no-caller": "error",
		"no-div-regex": "warn",
		"no-empty-function": "warn",
		"no-eval": "error",
		"no-extend-native": "error",
		"no-extra-bind": "error",
		"no-extra-label": "warn",
		"no-implicit-coercion": "error",
		"no-implicit-globals": "error",
		"no-implied-eval": "error",
		"no-invalid-this": "error",
		"no-iterator": "error",
		"no-lone-blocks": "error",
		"no-loop-func": "warn",
		"no-multi-str": "error",
		"no-new-func": "error",
		"no-new-wrappers": "error",
		"no-octal-escape": "error",
		"no-proto": "error",
		"no-script-url": "error",
		"no-self-compare": "error",
		"no-sequences": "error",
		"no-throw-literal": "error",
		"no-unused-expressions": "warn",
		"no-useless-call": "warn",
		"no-useless-concat": "warn",
		"no-void": "error",
		"prefer-promise-reject-errors": "warn",
		"radix": "error",
		"require-await": "warn",
		"require-unicode-regexp": "off",
		"vars-on-top": "warn",
		"yoda": "error",

		// Labels
		"no-labels": "error",
		"no-extra-label": "error",
		"no-unused-labels": "error",
		"no-label-var": "error",

		// Avoiding pitfalls
		"no-promise-executor-return": "error",
		"no-return-assign": "error",
		"no-constructor-return": "error",

		// Deviation from eslint:recommended
		"no-prototype-builtins": "off",
		"accessor-pairs": ["warn", {
			setWithoutGet: true,
		}],

		// Variables
		"no-label-var": "error",
		"no-undef-init": "error",
		"no-undefined": "error",
		"no-use-before-define": "warn",

		// Node.js
		"callback-return": "off",
		"global-require": "error",
		"no-buffer-constructor": "error",
		"no-mixed-requires": "error",
		"no-new-require": "error",
		"no-path-concat": "warn",
		"no-process-exit": "warn",

		// Style
		"camelcase": ["warn", {
			properties: "always",
			ignoreDestructuring: true,
		}],
		"consistent-this": "warn",
		"func-style": ["warn", "expression"],
		"max-depth": ["warn", {
			max: 10
		}],
		"max-nested-callbacks": ["warn", {
			max: 10
		}],
		"max-params": ["warn", {
			max: 10
		}],
		"new-cap": ["warn", {
			newIsCap: true,
			capIsNew: false,
			properties: true,
		}],
		"no-array-constructor": "error",
		"no-bitwise": "warn",
		"no-lonely-if": "warn",
		"no-multi-assign": "error",
		"no-negated-condition": "warn",
		"no-nested-ternary": "error",
		"no-new-object": "error",
		"no-plusplus": "warn",
		"no-underscore-dangle": ["warn", {
			enforceInMethodNames: false
		}],
		"one-var": ["warn", {
			var: "never",
			let: "never",
			const: "never",
			separateRequires: true,
		}],
		"operator-assignment": ["warn", "always"],
		"unicode-bom": ["warn", "never"],

		// ECMAScript 6
		"arrow-body-style": ["off"],
		"constructor-super": ["error"],
		"no-class-assign": ["error"],
		"no-duplicate-imports": ["error"],
		"no-this-before-super": ["warn"],
		"no-useless-computed-key": ["warn"],
		"no-useless-constructor": ["warn"],
		"no-var": ["error"],
		"object-shorthand": ["warn"],
		"prefer-arrow-callback": ["warn"],
		"prefer-const": ["warn"],
		"prefer-numeric-literals": ["warn"],
		"prefer-spread": ["warn"],
	}
}
