export const rules = {
	// Disable deprecated rules (for the most part, these rules have been replaced by
	// @stylistic and set in the following section)
	'array-bracket-newline': 'off',
	'array-bracket-spacing': 'off',
	'array-element-newline': 'off',
	'arrow-parens': 'off',
	'arrow-spacing': 'off',
	'block-spacing': 'off',
	'brace-style': 'off',
	'comma-dangle': 'off',
	'comma-spacing': 'off',
	'comma-style': 'off',
	'computed-property-spacing': 'off',
	'dot-location': 'off',
	'eol-last': 'off',
	'func-call-spacing': 'off',
	'function-call-argument-newline': 'off',
	'function-paren-newline': 'off',
	'generator-star-spacing': 'off',
	'implicit-arrow-linebreak': 'off',
	'indent': 'off',
	'jsx-quotes': 'off',
	'key-spacing': 'off',
	'keyword-spacing': 'off',
	'linebreak-style': 'off',
	'lines-between-class-members': 'off',
	'lines-around-comment': 'off',
	'max-len': 'off',
	'max-statements-per-line': 'off',
	'multiline-ternary': 'off',
	'new-parens': 'off',
	'newline-per-chained-call': 'off',
	'no-confusing-arrow': 'off',
	'no-extra-parens': 'off',
	'no-extra-semi': 'off',
	'no-floating-decimal': 'off',
	'no-mixed-operators': 'off',
	'no-mixed-spaces-and-tabs': 'off',
	'no-multi-spaces': 'off',
	'no-multiple-empty-lines': 'off',
	'no-tabs': 'off',
	'no-trailing-spaces': 'off',
	'no-whitespace-before-property': 'off',
	'nonblock-statement-body-position': 'off',
	'object-curly-newline': 'off',
	'object-curly-spacing': 'off',
	'object-property-newline': 'off',
	'one-var-declaration-per-line': 'off',
	'operator-linebreak': 'off',
	'padded-blocks': 'off',
	'padding-line-between-statements': 'off',
	'quote-props': 'off',
	'quotes': 'off',
	'rest-spread-spacing': 'off',
	'semi': 'off',
	'semi-spacing': 'off',
	'semi-style': 'off',
	'space-before-blocks': 'off',
	'space-before-function-paren': 'off',
	'space-in-parens': 'off',
	'space-infix-ops': 'off',
	'space-unary-ops': 'off',
	'spaced-comment': 'off',
	'switch-colon-spacing': 'off',
	'template-curly-spacing': 'off',
	'template-tag-spacing': 'off',
	'wrap-iife': 'off',
	'wrap-regex': 'off',
	'yield-star-spacing': 'off',

	// Stylistic
	'@stylistic/array-bracket-spacing': ['warn', 'never'],
	'@stylistic/arrow-spacing': ['warn', {
		before: true,
		after: true,
	}],
	'@stylistic/block-spacing': ['warn', 'always'],
	'@stylistic/brace-style': ['warn', '1tbs', {
		allowSingleLine: false,
	}],
	'@stylistic/comma-dangle': ['warn', {
		arrays: 'always-multiline',
		objects: 'always-multiline',
		imports: 'never',
		exports: 'never',
		functions: 'never',
	}],
	'@stylistic/comma-spacing': ['warn', {
		before: false,
		after: true,
	}],
	'@stylistic/comma-style': ['warn', 'last'],
	'@stylistic/computed-property-spacing': ['warn', 'never'],
	'@stylistic/dot-location': ['warn', 'property'],
	'@stylistic/eol-last': ['warn', 'always'],
	'@stylistic/function-call-argument-newline': ['warn', 'never'],
	'@stylistic/function-call-spacing': ['warn', 'never'],
	'@stylistic/function-paren-newline': ['warn', 'never'],
	'@stylistic/generator-star-spacing': ['warn', {
		before: false,
		after: true,
	}],
	'@stylistic/implicit-arrow-linebreak': ['warn', 'beside'],
	'@stylistic/key-spacing': ['warn', {
		singleLine: {
			mode: 'strict',
			beforeColon: false,
			afterColon: true,
		},
		multiLine: {
			mode: 'strict',
			beforeColon: false,
			afterColon: true,
		},
	}],
	'@stylistic/keyword-spacing': ['warn', {
		before: true,
		after: true,
	}],
	'@stylistic/linebreak-style': ['warn', 'unix'],
	'@stylistic/lines-between-class-members': ['warn', 'always', {
		exceptAfterSingleLine: true,
	}],
	'@stylistic/max-len': 'off',
	'@stylistic/max-statements-per-line': ['warn', {
		max: 1,
	}],
	'@stylistic/multiline-ternary': ['warn', 'never'],
	'@stylistic/new-parens': ['error', 'always'],
	'@stylistic/newline-per-chained-call': 'off',
	'@stylistic/no-confusing-arrow': ['warn', {
		allowParens: true,
	}],
	'@stylistic/no-extra-parens': 'off',
	'@stylistic/no-extra-semi': ['warn'],
	'@stylistic/no-floating-decimal': ['error'],
	'@stylistic/no-mixed-operators': ['warn'],
	'@stylistic/no-mixed-spaces-and-tabs': ['warn'],
	'@stylistic/no-multi-spaces': ['warn'],
	'@stylistic/no-multiple-empty-lines': ['warn', {
		max: 2,
	}],
	'@stylistic/no-tabs': 'off',
	'@stylistic/no-trailing-spaces': ['warn', {
		skipBlankLines: false,
		ignoreComments: false,
	}],
	'@stylistic/no-whitespace-before-property': ['error'],
	'@stylistic/nonblock-statement-body-position': ['error', 'beside'],
	'@stylistic/object-curly-spacing': ['warn', 'always'],
	'@stylistic/one-var-declaration-per-line': ['warn', 'always'],
	'@stylistic/operator-linebreak': ['warn', 'after'],
	'@stylistic/padded-blocks': ['warn', 'never'],
	'@stylistic/padding-line-between-statements': ['warn',
		{ blankLine: 'always', prev: '*', next: 'if' },
	],
	'@stylistic/quote-props': ['warn', 'consistent-as-needed'],
	'@stylistic/quotes': ['warn', 'single', {
		avoidEscape: true,
		allowTemplateLiterals: 'never',
	}],
	'@stylistic/rest-spread-spacing': ['error', 'never'],
	'@stylistic/semi': ['warn', 'always'],
	'@stylistic/semi-spacing': ['warn', {
		before: false,
		after: true,
	}],
	'@stylistic/semi-style': ['warn', 'last'],
	'@stylistic/space-before-blocks': ['warn', 'always'],
	'@stylistic/space-before-function-paren': ['warn', {
		anonymous: 'always',
		named: 'never',
		asyncArrow: 'always',
	}],
	'@stylistic/space-in-parens': ['warn', 'never'],
	'@stylistic/space-infix-ops': ['error'],
	'@stylistic/space-unary-ops': ['warn'],
	'@stylistic/spaced-comment': ['warn', 'always', {
		exceptions: ['/', '*', '!'],
	}],
	'@stylistic/switch-colon-spacing': ['warn', {
		before: false,
		after: true,
	}],
	'@stylistic/template-curly-spacing': ['warn', 'always'],
	'@stylistic/template-tag-spacing': ['warn', 'never'],
	'@stylistic/wrap-iife': ['warn', 'outside'],
	'@stylistic/wrap-regex': 'off',
	'@stylistic/yield-star-spacing': ['warn', 'after'],

	// Possible errors
	'no-await-in-loop': 'warn',
	'no-control-regex': 'warn',
	'no-debugger': 'warn',
	'no-empty': 'warn',
	'no-extra-boolean-cast': 'warn',
	'no-template-curly-in-string': 'warn',
	'no-unreachable': 'warn',

	// Best practises
	'array-callback-return': 'error',
	'block-scoped-var': 'warn',
	'consistent-return': 'warn',
	'curly': 'error',
	'dot-notation': 'warn',
	'eqeqeq': ['error', 'smart'],
	'guard-for-in': 'warn',
	'max-classes-per-file': ['warn', 1],
	'no-alert': 'error',
	'no-caller': 'error',
	'no-div-regex': 'warn',
	'no-empty-function': 'warn',
	'no-eval': 'error',
	'no-extend-native': 'error',
	'no-extra-bind': 'error',
	'no-implicit-coercion': 'error',
	'no-implicit-globals': 'error',
	'no-implied-eval': 'error',
	'no-invalid-this': 'error',
	'no-iterator': 'error',
	'no-lone-blocks': 'error',
	'no-loop-func': 'warn',
	'no-multi-str': 'error',
	'no-new-func': 'error',
	'no-new-wrappers': 'error',
	'no-octal-escape': 'error',
	'no-proto': 'error',
	'no-script-url': 'error',
	'no-self-compare': 'error',
	'no-sequences': 'error',
	'no-throw-literal': 'error',
	'no-unused-expressions': 'warn',
	'no-useless-call': 'warn',
	'no-useless-concat': 'warn',
	'no-void': 'error',
	'prefer-promise-reject-errors': 'warn',
	'radix': 'error',
	'require-await': 'warn',
	'require-unicode-regexp': 'off',
	'vars-on-top': 'warn',
	'yoda': 'error',

	// Labels
	'no-labels': 'error',
	'no-extra-label': 'error',
	'no-unused-labels': 'error',
	'no-label-var': 'error',

	// Avoiding pitfalls
	'no-promise-executor-return': 'error',
	'no-return-assign': 'error',
	'no-constructor-return': 'error',

	// Deviation from eslint:recommended
	'no-prototype-builtins': 'off',
	'accessor-pairs': ['warn', {
		setWithoutGet: true,
	}],

	// Variables
	'no-undef-init': 'error',
	'no-undefined': 'error',
	'no-use-before-define': 'warn',

	// Node.js
	'callback-return': 'off',
	'global-require': 'error',
	'no-buffer-constructor': 'error',
	'no-mixed-requires': 'error',
	'no-new-require': 'error',
	'no-path-concat': 'warn',
	'no-process-exit': 'warn',

	// Style
	'camelcase': ['warn', {
		properties: 'always',
		ignoreDestructuring: true,
	}],
	'consistent-this': 'warn',
	'func-style': ['warn', 'expression'],
	'max-depth': ['warn', {
		max: 10,
	}],
	'max-nested-callbacks': ['warn', {
		max: 10,
	}],
	'max-params': ['warn', {
		max: 10,
	}],
	'new-cap': ['warn', {
		newIsCap: true,
		capIsNew: false,
		properties: true,
	}],
	'no-array-constructor': 'error',
	'no-bitwise': 'warn',
	'no-lonely-if': 'warn',
	'no-multi-assign': 'error',
	'no-negated-condition': 'warn',
	'no-nested-ternary': 'error',
	'no-new-object': 'error',
	'no-plusplus': 'warn',
	'no-underscore-dangle': ['warn', {
		enforceInMethodNames: false,
	}],
	'one-var': ['warn', {
		var: 'never',
		let: 'never',
		const: 'never',
		separateRequires: true,
	}],
	'operator-assignment': ['warn', 'always'],
	'unicode-bom': ['warn', 'never'],

	// ECMAScript 6
	'arrow-body-style': 'off',
	'constructor-super': ['error'],
	'no-class-assign': ['error'],
	'no-duplicate-imports': ['error'],
	'no-this-before-super': ['warn'],
	'no-useless-computed-key': ['warn'],
	'no-useless-constructor': ['warn'],
	'no-var': ['error'],
	'object-shorthand': ['warn'],
	'prefer-arrow-callback': ['warn'],
	'prefer-const': ['warn'],
	'prefer-numeric-literals': ['warn'],
	'prefer-spread': ['warn'],
};
